### ISSUE TITLE
TODO's pre-commit-vauxoo

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/pre-commit-vauxoo#1]
# PRE-COMMIT
- [x] Use flake bear plugin as optional
  - https://github.com/Vauxoo/pre-commit-vauxoo/pull/8
- [ ] Move autofixes that already are not fixing to optional (example, shebangs)
- [x] Add --install-hook to auto run pre-commit-vauxoo for each git commit automatically
- [x] <s>Add rst-lint to pre-commit and configure the pre-commit of the repository</s> `tox -e docs` instead
- [x] Run the unittests with click 6.6 since it was failing in the deployv docker image
- [x] Run with deployv docker image
- [x] Generates pypi packages with auto-releases from github action
- [x] Fix codecov error uploading from macosx, windows bc token
- [x] Migrate commits to release notes for pypi
  - https://github.com/Vauxoo/pre-commit-vauxoo/pull/28
  - https://github.com/Vauxoo/pre-commit-vauxoo/pull/29
- [x] Implement auto-cancelation github action: https://github.com/marketplace/actions/auto-cancellation-running-action
- [x] Add pre-commit cache to github actions
- [x] Check if there is a way to skip for py3.6 the hook https://github.com/pre-commit/pre-commit-hooks since it is not compatible anymore
  - https://github.com/Vauxoo/pre-commit-vauxoo/pull/10
- [x] exclude paths for autofixes
- [x] Use dynamic checkers...?
- [x] Send all the pre-commit sub-commands from pre-commit-vauxoo (wrapper)
- [x] Use jinja2 in order to create the configuration files
  - similar to https://github.com/OCA/oca-addons-repo-template/tree/master/src
- [x] Allow to run pre-commit-vauxoo only for current folder
- [x] Add command parameter matching with environment variables
  - https://github.com/Vauxoo/pre-commit-vauxoo/pull/23
- [x] Pre-install autofix if it was enabled
- [x] Get the .git dir from path folder
  - https://github.com/Vauxoo/pre-commit-vauxoo/pull/2
- [x] Return a status for warning (fails allowed, warn: -1, error: 1, good: 0) in order to call pre-commit for warnings pipeline
  - add to .gitlab-ci.yml a lint-warnings allow to fail with !=0 but using a parameter or env-variable `--optional` or `PRECOMMIT_OPTIONAL`
    - https://github.com/Vauxoo/pre-commit-vauxoo/pull/35
- [x] Add --help with documentation
  - https://github.com/Vauxoo/pre-commit-vauxoo/pull/23
- [x] <s>Remove configuration files created (I still am not sure to do it) </s> Better adding to gitignore
- [x] Add the following command options: --autofix --mandatory --optional 
- [x] Autofix light or hard
- [x] Define experimental configuration files in order to show without affecting status but no red, no warning...

- [x] Add the following command options: --only-copy-files --replace-config-file

# DEPLOYV
- [x] Run tests for odoo-sh projects & apps projects as vx/mx
- [x] coveragerc use the environment variable to discard paths
- [x] t2d subcommand to build deployv test environment
- [x] Ignore pywarnings
